services:
  db:
    container_name: postgres
    image: postgres
    env_file: ../../.env
    ports:
      - 5432:5432
  webapp:
    build: 
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      db: 
        condition: service_started
