services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: ../../.env
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4 
    ports: 
      - 8080:80
    env_file: ../../.env
